// This file is auto-generated by @hey-api/openapi-ts

import {
  type Client,
  type ClientMeta,
  formDataBodySerializer,
  type Options as Options2,
  type RequestResult,
  type TDataShape,
  urlSearchParamsBodySerializer,
} from './client';
import { client } from './client.gen';
import type {
  ActivateNextStageTournamentsTournamentIdStagesActivatePostData,
  ActivateNextStageTournamentsTournamentIdStagesActivatePostErrors,
  ActivateNextStageTournamentsTournamentIdStagesActivatePostResponses,
  ChangeStatusTournamentsTournamentIdChangeStatusPostData,
  ChangeStatusTournamentsTournamentIdChangeStatusPostErrors,
  ChangeStatusTournamentsTournamentIdChangeStatusPostResponses,
  CreateCourtTournamentsTournamentIdCourtsPostData,
  CreateCourtTournamentsTournamentIdCourtsPostErrors,
  CreateCourtTournamentsTournamentIdCourtsPostResponses,
  CreateEventTournamentsTournamentIdEventsPostData,
  CreateEventTournamentsTournamentIdEventsPostErrors,
  CreateEventTournamentsTournamentIdEventsPostResponses,
  CreateMatchTournamentsTournamentIdMatchesPostData,
  CreateMatchTournamentsTournamentIdMatchesPostErrors,
  CreateMatchTournamentsTournamentIdMatchesPostResponses,
  CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostData,
  CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostErrors,
  CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostResponses,
  CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostData,
  CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostErrors,
  CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostResponses,
  CreateNewClubClubsPostData,
  CreateNewClubClubsPostErrors,
  CreateNewClubClubsPostResponses,
  CreateRankingTournamentsTournamentIdRankingsPostData,
  CreateRankingTournamentsTournamentIdRankingsPostErrors,
  CreateRankingTournamentsTournamentIdRankingsPostResponses,
  CreateRoundTournamentsTournamentIdRoundsPostData,
  CreateRoundTournamentsTournamentIdRoundsPostErrors,
  CreateRoundTournamentsTournamentIdRoundsPostResponses,
  CreateSinglePlayerTournamentsTournamentIdPlayersPostData,
  CreateSinglePlayerTournamentsTournamentIdPlayersPostErrors,
  CreateSinglePlayerTournamentsTournamentIdPlayersPostResponses,
  CreateStageItemTournamentsTournamentIdStageItemsPostData,
  CreateStageItemTournamentsTournamentIdStageItemsPostErrors,
  CreateStageItemTournamentsTournamentIdStageItemsPostResponses,
  CreateStageTournamentsTournamentIdStagesPostData,
  CreateStageTournamentsTournamentIdStagesPostErrors,
  CreateStageTournamentsTournamentIdStagesPostResponses,
  CreateTeamTournamentsTournamentIdTeamsPostData,
  CreateTeamTournamentsTournamentIdTeamsPostErrors,
  CreateTeamTournamentsTournamentIdTeamsPostResponses,
  CreateTournamentTournamentsPostData,
  CreateTournamentTournamentsPostErrors,
  CreateTournamentTournamentsPostResponses,
  DeleteClubClubsClubIdDeleteData,
  DeleteClubClubsClubIdDeleteErrors,
  DeleteClubClubsClubIdDeleteResponses,
  DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteData,
  DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteErrors,
  DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteResponses,
  DeleteEventTournamentsTournamentIdEventsEventIdDeleteData,
  DeleteEventTournamentsTournamentIdEventsEventIdDeleteErrors,
  DeleteEventTournamentsTournamentIdEventsEventIdDeleteResponses,
  DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteData,
  DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteErrors,
  DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteResponses,
  DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteData,
  DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteErrors,
  DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteResponses,
  DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteData,
  DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteErrors,
  DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteResponses,
  DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteData,
  DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteErrors,
  DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteResponses,
  DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteData,
  DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteErrors,
  DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteResponses,
  DeleteStageTournamentsTournamentIdStagesStageIdDeleteData,
  DeleteStageTournamentsTournamentIdStagesStageIdDeleteErrors,
  DeleteStageTournamentsTournamentIdStagesStageIdDeleteResponses,
  DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteData,
  DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteErrors,
  DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteResponses,
  DeleteTournamentTournamentsTournamentIdDeleteData,
  DeleteTournamentTournamentsTournamentIdDeleteErrors,
  DeleteTournamentTournamentsTournamentIdDeleteResponses,
  GetAvailableInputsTournamentsTournamentIdAvailableInputsGetData,
  GetAvailableInputsTournamentsTournamentIdAvailableInputsGetErrors,
  GetAvailableInputsTournamentsTournamentIdAvailableInputsGetResponses,
  GetClubsClubsGetData,
  GetClubsClubsGetResponses,
  GetCourtsTournamentsTournamentIdCourtsGetData,
  GetCourtsTournamentsTournamentIdCourtsGetErrors,
  GetCourtsTournamentsTournamentIdCourtsGetResponses,
  GetEventsTournamentsTournamentIdEventsGetData,
  GetEventsTournamentsTournamentIdEventsGetErrors,
  GetEventsTournamentsTournamentIdEventsGetResponses,
  GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetData,
  GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetErrors,
  GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetResponses,
  GetMetricsMetricsGetData,
  GetMetricsMetricsGetResponses,
  GetMeUsersUserIdGetData,
  GetMeUsersUserIdGetErrors,
  GetMeUsersUserIdGetResponses,
  GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetData,
  GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetErrors,
  GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetResponses,
  GetPlayersTournamentsTournamentIdPlayersGetData,
  GetPlayersTournamentsTournamentIdPlayersGetErrors,
  GetPlayersTournamentsTournamentIdPlayersGetResponses,
  GetRankingsTournamentsTournamentIdRankingsGetData,
  GetRankingsTournamentsTournamentIdRankingsGetErrors,
  GetRankingsTournamentsTournamentIdRankingsGetResponses,
  GetStagesTournamentsTournamentIdStagesGetData,
  GetStagesTournamentsTournamentIdStagesGetErrors,
  GetStagesTournamentsTournamentIdStagesGetResponses,
  GetTeamsTournamentsTournamentIdTeamsGetData,
  GetTeamsTournamentsTournamentIdTeamsGetErrors,
  GetTeamsTournamentsTournamentIdTeamsGetResponses,
  GetTournamentsTournamentsGetData,
  GetTournamentsTournamentsGetErrors,
  GetTournamentsTournamentsGetResponses,
  GetTournamentTournamentsTournamentIdGetData,
  GetTournamentTournamentsTournamentIdGetErrors,
  GetTournamentTournamentsTournamentIdGetResponses,
  GetUserUsersMeGetData,
  GetUserUsersMeGetResponses,
  LoginForAccessTokenTokenPostData,
  LoginForAccessTokenTokenPostErrors,
  LoginForAccessTokenTokenPostResponses,
  MergeTeamTournamentsTournamentIdTeamsTeamIdMergePostData,
  MergeTeamTournamentsTournamentIdTeamsTeamIdMergePostErrors,
  MergeTeamTournamentsTournamentIdTeamsTeamIdMergePostResponses,
  PingPingGetData,
  PingPingGetResponses,
  PutUserPasswordUsersUserIdPasswordPutData,
  PutUserPasswordUsersUserIdPasswordPutErrors,
  PutUserPasswordUsersUserIdPasswordPutResponses,
  RegisterDemoUserUsersRegisterDemoPostData,
  RegisterDemoUserUsersRegisterDemoPostErrors,
  RegisterDemoUserUsersRegisterDemoPostResponses,
  RegisterTeamTournamentsTournamentIdRegisterPostData,
  RegisterTeamTournamentsTournamentIdRegisterPostErrors,
  RegisterTeamTournamentsTournamentIdRegisterPostResponses,
  RegisterUserUsersRegisterPostData,
  RegisterUserUsersRegisterPostErrors,
  RegisterUserUsersRegisterPostResponses,
  RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostData,
  RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostErrors,
  RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostResponses,
  ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostData,
  ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostErrors,
  ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostResponses,
  SplitTeamTournamentsTournamentIdTeamsTeamIdSplitPostData,
  SplitTeamTournamentsTournamentIdTeamsTeamIdSplitPostErrors,
  SplitTeamTournamentsTournamentIdTeamsTeamIdSplitPostResponses,
  StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostData,
  StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostErrors,
  StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostResponses,
  UpdateClubClubsClubIdPutData,
  UpdateClubClubsClubIdPutErrors,
  UpdateClubClubsClubIdPutResponses,
  UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutData,
  UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutErrors,
  UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutResponses,
  UpdateEventTournamentsTournamentIdEventsEventIdPutData,
  UpdateEventTournamentsTournamentIdEventsEventIdPutErrors,
  UpdateEventTournamentsTournamentIdEventsEventIdPutResponses,
  UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutData,
  UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutErrors,
  UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutResponses,
  UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutData,
  UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutErrors,
  UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutResponses,
  UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutData,
  UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutErrors,
  UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutResponses,
  UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutData,
  UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutErrors,
  UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutResponses,
  UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutData,
  UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutErrors,
  UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponses,
  UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutData,
  UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutErrors,
  UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutResponses,
  UpdateStageTournamentsTournamentIdStagesStageIdPutData,
  UpdateStageTournamentsTournamentIdStagesStageIdPutErrors,
  UpdateStageTournamentsTournamentIdStagesStageIdPutResponses,
  UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutData,
  UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutErrors,
  UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutResponses,
  UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostData,
  UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostErrors,
  UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostResponses,
  UpdateTournamentByIdTournamentsTournamentIdPutData,
  UpdateTournamentByIdTournamentsTournamentIdPutErrors,
  UpdateTournamentByIdTournamentsTournamentIdPutResponses,
  UpdateUserDetailsUsersUserIdPutData,
  UpdateUserDetailsUsersUserIdPutErrors,
  UpdateUserDetailsUsersUserIdPutResponses,
  UploadLogoTournamentsTournamentIdLogoPostData,
  UploadLogoTournamentsTournamentIdLogoPostErrors,
  UploadLogoTournamentsTournamentIdLogoPostResponses,
} from './types.gen';

export type Options<
  TData extends TDataShape = TDataShape,
  ThrowOnError extends boolean = boolean,
  TResponse = unknown,
> = Options2<TData, ThrowOnError, TResponse> & {
  /**
   * You can provide a client instance returned by `createClient()` instead of
   * individual options. This might be also useful if you want to implement a
   * custom client.
   */
  client?: Client;
  /**
   * You can pass arbitrary values through the `meta` object. This can be
   * used to access values that aren't defined as part of the SDK function.
   */
  meta?: keyof ClientMeta extends never ? Record<string, unknown> : ClientMeta;
};

/**
 * Get Clubs
 */
export const getClubsClubsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetClubsClubsGetData, ThrowOnError>,
): RequestResult<GetClubsClubsGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetClubsClubsGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clubs',
    ...options,
  });

/**
 * Create New Club
 */
export const createNewClubClubsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateNewClubClubsPostData, ThrowOnError>,
): RequestResult<CreateNewClubClubsPostResponses, CreateNewClubClubsPostErrors, ThrowOnError> =>
  (options.client ?? client).post<
    CreateNewClubClubsPostResponses,
    CreateNewClubClubsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clubs',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Club
 */
export const deleteClubClubsClubIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteClubClubsClubIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteClubClubsClubIdDeleteResponses,
  DeleteClubClubsClubIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteClubClubsClubIdDeleteResponses,
    DeleteClubClubsClubIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clubs/{club_id}',
    ...options,
  });

/**
 * Update Club
 */
export const updateClubClubsClubIdPut = <ThrowOnError extends boolean = false>(
  options: Options<UpdateClubClubsClubIdPutData, ThrowOnError>,
): RequestResult<UpdateClubClubsClubIdPutResponses, UpdateClubClubsClubIdPutErrors, ThrowOnError> =>
  (options.client ?? client).put<
    UpdateClubClubsClubIdPutResponses,
    UpdateClubClubsClubIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/clubs/{club_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Metrics
 */
export const getMetricsMetricsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetMetricsMetricsGetData, ThrowOnError>,
): RequestResult<GetMetricsMetricsGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetMetricsMetricsGetResponses, unknown, ThrowOnError>({
    responseType: 'text',
    url: '/metrics',
    ...options,
  });

/**
 * Healthcheck ping
 */
export const pingPingGet = <ThrowOnError extends boolean = false>(
  options?: Options<PingPingGetData, ThrowOnError>,
): RequestResult<PingPingGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<PingPingGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    url: '/ping',
    ...options,
  });

/**
 * Login For Access Token
 */
export const loginForAccessTokenTokenPost = <ThrowOnError extends boolean = false>(
  options: Options<LoginForAccessTokenTokenPostData, ThrowOnError>,
): RequestResult<
  LoginForAccessTokenTokenPostResponses,
  LoginForAccessTokenTokenPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    LoginForAccessTokenTokenPostResponses,
    LoginForAccessTokenTokenPostErrors,
    ThrowOnError
  >({
    ...urlSearchParamsBodySerializer,
    responseType: 'json',
    url: '/token',
    ...options,
    headers: {
      'Content-Type': 'application/x-www-form-urlencoded',
      ...options.headers,
    },
  });

/**
 * Get Tournaments
 */
export const getTournamentsTournamentsGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetTournamentsTournamentsGetData, ThrowOnError>,
): RequestResult<
  GetTournamentsTournamentsGetResponses,
  GetTournamentsTournamentsGetErrors,
  ThrowOnError
> =>
  (options?.client ?? client).get<
    GetTournamentsTournamentsGetResponses,
    GetTournamentsTournamentsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments',
    ...options,
  });

/**
 * Create Tournament
 */
export const createTournamentTournamentsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateTournamentTournamentsPostData, ThrowOnError>,
): RequestResult<
  CreateTournamentTournamentsPostResponses,
  CreateTournamentTournamentsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateTournamentTournamentsPostResponses,
    CreateTournamentTournamentsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Tournament
 */
export const deleteTournamentTournamentsTournamentIdDelete = <ThrowOnError extends boolean = false>(
  options: Options<DeleteTournamentTournamentsTournamentIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteTournamentTournamentsTournamentIdDeleteResponses,
  DeleteTournamentTournamentsTournamentIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteTournamentTournamentsTournamentIdDeleteResponses,
    DeleteTournamentTournamentsTournamentIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}',
    ...options,
  });

/**
 * Get Tournament
 */
export const getTournamentTournamentsTournamentIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetTournamentTournamentsTournamentIdGetData, ThrowOnError>,
): RequestResult<
  GetTournamentTournamentsTournamentIdGetResponses,
  GetTournamentTournamentsTournamentIdGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetTournamentTournamentsTournamentIdGetResponses,
    GetTournamentTournamentsTournamentIdGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}',
    ...options,
  });

/**
 * Update Tournament By Id
 */
export const updateTournamentByIdTournamentsTournamentIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateTournamentByIdTournamentsTournamentIdPutData, ThrowOnError>,
): RequestResult<
  UpdateTournamentByIdTournamentsTournamentIdPutResponses,
  UpdateTournamentByIdTournamentsTournamentIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateTournamentByIdTournamentsTournamentIdPutResponses,
    UpdateTournamentByIdTournamentsTournamentIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Available Inputs
 */
export const getAvailableInputsTournamentsTournamentIdAvailableInputsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<GetAvailableInputsTournamentsTournamentIdAvailableInputsGetData, ThrowOnError>,
): RequestResult<
  GetAvailableInputsTournamentsTournamentIdAvailableInputsGetResponses,
  GetAvailableInputsTournamentsTournamentIdAvailableInputsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetAvailableInputsTournamentsTournamentIdAvailableInputsGetResponses,
    GetAvailableInputsTournamentsTournamentIdAvailableInputsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/available_inputs',
    ...options,
  });

/**
 * Change Status
 *
 * Make a tournament archived or non-archived.
 */
export const changeStatusTournamentsTournamentIdChangeStatusPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ChangeStatusTournamentsTournamentIdChangeStatusPostData, ThrowOnError>,
): RequestResult<
  ChangeStatusTournamentsTournamentIdChangeStatusPostResponses,
  ChangeStatusTournamentsTournamentIdChangeStatusPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ChangeStatusTournamentsTournamentIdChangeStatusPostResponses,
    ChangeStatusTournamentsTournamentIdChangeStatusPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/change-status',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Courts
 */
export const getCourtsTournamentsTournamentIdCourtsGet = <ThrowOnError extends boolean = false>(
  options: Options<GetCourtsTournamentsTournamentIdCourtsGetData, ThrowOnError>,
): RequestResult<
  GetCourtsTournamentsTournamentIdCourtsGetResponses,
  GetCourtsTournamentsTournamentIdCourtsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetCourtsTournamentsTournamentIdCourtsGetResponses,
    GetCourtsTournamentsTournamentIdCourtsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/courts',
    ...options,
  });

/**
 * Create Court
 */
export const createCourtTournamentsTournamentIdCourtsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateCourtTournamentsTournamentIdCourtsPostData, ThrowOnError>,
): RequestResult<
  CreateCourtTournamentsTournamentIdCourtsPostResponses,
  CreateCourtTournamentsTournamentIdCourtsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateCourtTournamentsTournamentIdCourtsPostResponses,
    CreateCourtTournamentsTournamentIdCourtsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/courts',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Court
 */
export const deleteCourtTournamentsTournamentIdCourtsCourtIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteResponses,
  DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteResponses,
    DeleteCourtTournamentsTournamentIdCourtsCourtIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/courts/{court_id}',
    ...options,
  });

/**
 * Update Court By Id
 */
export const updateCourtByIdTournamentsTournamentIdCourtsCourtIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutData, ThrowOnError>,
): RequestResult<
  UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutResponses,
  UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutResponses,
    UpdateCourtByIdTournamentsTournamentIdCourtsCourtIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/courts/{court_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Events
 */
export const getEventsTournamentsTournamentIdEventsGet = <ThrowOnError extends boolean = false>(
  options: Options<GetEventsTournamentsTournamentIdEventsGetData, ThrowOnError>,
): RequestResult<
  GetEventsTournamentsTournamentIdEventsGetResponses,
  GetEventsTournamentsTournamentIdEventsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetEventsTournamentsTournamentIdEventsGetResponses,
    GetEventsTournamentsTournamentIdEventsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/events',
    ...options,
  });

/**
 * Create Event
 */
export const createEventTournamentsTournamentIdEventsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateEventTournamentsTournamentIdEventsPostData, ThrowOnError>,
): RequestResult<
  CreateEventTournamentsTournamentIdEventsPostResponses,
  CreateEventTournamentsTournamentIdEventsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateEventTournamentsTournamentIdEventsPostResponses,
    CreateEventTournamentsTournamentIdEventsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/events',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Event
 */
export const deleteEventTournamentsTournamentIdEventsEventIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteEventTournamentsTournamentIdEventsEventIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteEventTournamentsTournamentIdEventsEventIdDeleteResponses,
  DeleteEventTournamentsTournamentIdEventsEventIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteEventTournamentsTournamentIdEventsEventIdDeleteResponses,
    DeleteEventTournamentsTournamentIdEventsEventIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/events/{event_id}',
    ...options,
  });

/**
 * Update Event
 */
export const updateEventTournamentsTournamentIdEventsEventIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateEventTournamentsTournamentIdEventsEventIdPutData, ThrowOnError>,
): RequestResult<
  UpdateEventTournamentsTournamentIdEventsEventIdPutResponses,
  UpdateEventTournamentsTournamentIdEventsEventIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateEventTournamentsTournamentIdEventsEventIdPutResponses,
    UpdateEventTournamentsTournamentIdEventsEventIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/events/{event_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Upload Logo
 */
export const uploadLogoTournamentsTournamentIdLogoPost = <ThrowOnError extends boolean = false>(
  options: Options<UploadLogoTournamentsTournamentIdLogoPostData, ThrowOnError>,
): RequestResult<
  UploadLogoTournamentsTournamentIdLogoPostResponses,
  UploadLogoTournamentsTournamentIdLogoPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    UploadLogoTournamentsTournamentIdLogoPostResponses,
    UploadLogoTournamentsTournamentIdLogoPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/logo',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Create Match
 */
export const createMatchTournamentsTournamentIdMatchesPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateMatchTournamentsTournamentIdMatchesPostData, ThrowOnError>,
): RequestResult<
  CreateMatchTournamentsTournamentIdMatchesPostResponses,
  CreateMatchTournamentsTournamentIdMatchesPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateMatchTournamentsTournamentIdMatchesPostResponses,
    CreateMatchTournamentsTournamentIdMatchesPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/matches',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Match
 */
export const deleteMatchTournamentsTournamentIdMatchesMatchIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteResponses,
  DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteResponses,
    DeleteMatchTournamentsTournamentIdMatchesMatchIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/matches/{match_id}',
    ...options,
  });

/**
 * Update Match By Id
 */
export const updateMatchByIdTournamentsTournamentIdMatchesMatchIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutData, ThrowOnError>,
): RequestResult<
  UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutResponses,
  UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutResponses,
    UpdateMatchByIdTournamentsTournamentIdMatchesMatchIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/matches/{match_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Reschedule Match
 */
export const rescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostData,
    ThrowOnError
  >,
): RequestResult<
  RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostResponses,
  RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostResponses,
    RescheduleMatchTournamentsTournamentIdMatchesMatchIdReschedulePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/matches/{match_id}/reschedule',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Next Stage Rankings
 *
 * Get the rankings for the stage items in this stage.
 */
export const getNextStageRankingsTournamentsTournamentIdNextStageRankingsGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetData,
    ThrowOnError
  >,
): RequestResult<
  GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetResponses,
  GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetResponses,
    GetNextStageRankingsTournamentsTournamentIdNextStageRankingsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/next_stage_rankings',
    ...options,
  });

/**
 * Get Players
 */
export const getPlayersTournamentsTournamentIdPlayersGet = <ThrowOnError extends boolean = false>(
  options: Options<GetPlayersTournamentsTournamentIdPlayersGetData, ThrowOnError>,
): RequestResult<
  GetPlayersTournamentsTournamentIdPlayersGetResponses,
  GetPlayersTournamentsTournamentIdPlayersGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetPlayersTournamentsTournamentIdPlayersGetResponses,
    GetPlayersTournamentsTournamentIdPlayersGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/players',
    ...options,
  });

/**
 * Create Single Player
 */
export const createSinglePlayerTournamentsTournamentIdPlayersPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateSinglePlayerTournamentsTournamentIdPlayersPostData, ThrowOnError>,
): RequestResult<
  CreateSinglePlayerTournamentsTournamentIdPlayersPostResponses,
  CreateSinglePlayerTournamentsTournamentIdPlayersPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateSinglePlayerTournamentsTournamentIdPlayersPostResponses,
    CreateSinglePlayerTournamentsTournamentIdPlayersPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/players',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Player
 */
export const deletePlayerTournamentsTournamentIdPlayersPlayerIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteData, ThrowOnError>,
): RequestResult<
  DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteResponses,
  DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteResponses,
    DeletePlayerTournamentsTournamentIdPlayersPlayerIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/players/{player_id}',
    ...options,
  });

/**
 * Update Player By Id
 */
export const updatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutData, ThrowOnError>,
): RequestResult<
  UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutResponses,
  UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutResponses,
    UpdatePlayerByIdTournamentsTournamentIdPlayersPlayerIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/players/{player_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create Multiple Players
 */
export const createMultiplePlayersTournamentsTournamentIdPlayersMultiPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostData, ThrowOnError>,
): RequestResult<
  CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostResponses,
  CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostResponses,
    CreateMultiplePlayersTournamentsTournamentIdPlayersMultiPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/players_multi',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Rankings
 */
export const getRankingsTournamentsTournamentIdRankingsGet = <ThrowOnError extends boolean = false>(
  options: Options<GetRankingsTournamentsTournamentIdRankingsGetData, ThrowOnError>,
): RequestResult<
  GetRankingsTournamentsTournamentIdRankingsGetResponses,
  GetRankingsTournamentsTournamentIdRankingsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetRankingsTournamentsTournamentIdRankingsGetResponses,
    GetRankingsTournamentsTournamentIdRankingsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/rankings',
    ...options,
  });

/**
 * Create Ranking
 */
export const createRankingTournamentsTournamentIdRankingsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateRankingTournamentsTournamentIdRankingsPostData, ThrowOnError>,
): RequestResult<
  CreateRankingTournamentsTournamentIdRankingsPostResponses,
  CreateRankingTournamentsTournamentIdRankingsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateRankingTournamentsTournamentIdRankingsPostResponses,
    CreateRankingTournamentsTournamentIdRankingsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/rankings',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Ranking
 */
export const deleteRankingTournamentsTournamentIdRankingsRankingIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteResponses,
  DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteResponses,
    DeleteRankingTournamentsTournamentIdRankingsRankingIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/rankings/{ranking_id}',
    ...options,
  });

/**
 * Update Ranking By Id
 */
export const updateRankingByIdTournamentsTournamentIdRankingsRankingIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutData, ThrowOnError>,
): RequestResult<
  UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutResponses,
  UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutResponses,
    UpdateRankingByIdTournamentsTournamentIdRankingsRankingIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/rankings/{ranking_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Register Team
 */
export const registerTeamTournamentsTournamentIdRegisterPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<RegisterTeamTournamentsTournamentIdRegisterPostData, ThrowOnError>,
): RequestResult<
  RegisterTeamTournamentsTournamentIdRegisterPostResponses,
  RegisterTeamTournamentsTournamentIdRegisterPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RegisterTeamTournamentsTournamentIdRegisterPostResponses,
    RegisterTeamTournamentsTournamentIdRegisterPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create Round
 */
export const createRoundTournamentsTournamentIdRoundsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateRoundTournamentsTournamentIdRoundsPostData, ThrowOnError>,
): RequestResult<
  CreateRoundTournamentsTournamentIdRoundsPostResponses,
  CreateRoundTournamentsTournamentIdRoundsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateRoundTournamentsTournamentIdRoundsPostResponses,
    CreateRoundTournamentsTournamentIdRoundsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/rounds',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Round
 */
export const deleteRoundTournamentsTournamentIdRoundsRoundIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteResponses,
  DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteResponses,
    DeleteRoundTournamentsTournamentIdRoundsRoundIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/rounds/{round_id}',
    ...options,
  });

/**
 * Update Round By Id
 */
export const updateRoundByIdTournamentsTournamentIdRoundsRoundIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutData, ThrowOnError>,
): RequestResult<
  UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutResponses,
  UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutResponses,
    UpdateRoundByIdTournamentsTournamentIdRoundsRoundIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/rounds/{round_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Schedule Matches
 */
export const scheduleMatchesTournamentsTournamentIdScheduleMatchesPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostData, ThrowOnError>,
): RequestResult<
  ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostResponses,
  ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostResponses,
    ScheduleMatchesTournamentsTournamentIdScheduleMatchesPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/schedule_matches',
    ...options,
  });

/**
 * Create Stage Item
 */
export const createStageItemTournamentsTournamentIdStageItemsPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateStageItemTournamentsTournamentIdStageItemsPostData, ThrowOnError>,
): RequestResult<
  CreateStageItemTournamentsTournamentIdStageItemsPostResponses,
  CreateStageItemTournamentsTournamentIdStageItemsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateStageItemTournamentsTournamentIdStageItemsPostResponses,
    CreateStageItemTournamentsTournamentIdStageItemsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stage_items',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Stage Item
 */
export const deleteStageItemTournamentsTournamentIdStageItemsStageItemIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteData,
    ThrowOnError
  >,
): RequestResult<
  DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteResponses,
  DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteResponses,
    DeleteStageItemTournamentsTournamentIdStageItemsStageItemIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stage_items/{stage_item_id}',
    ...options,
  });

/**
 * Update Stage Item
 */
export const updateStageItemTournamentsTournamentIdStageItemsStageItemIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutData,
    ThrowOnError
  >,
): RequestResult<
  UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutResponses,
  UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutResponses,
    UpdateStageItemTournamentsTournamentIdStageItemsStageItemIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stage_items/{stage_item_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update Stage Item Input
 */
export const updateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPut =
  <ThrowOnError extends boolean = false>(
    options: Options<
      UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutData,
      ThrowOnError
    >,
  ): RequestResult<
    UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponses,
    UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutErrors,
    ThrowOnError
  > =>
    (options.client ?? client).put<
      UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutResponses,
      UpdateStageItemInputTournamentsTournamentIdStageItemsStageItemIdInputsStageItemInputIdPutErrors,
      ThrowOnError
    >({
      responseType: 'json',
      security: [{ scheme: 'bearer', type: 'http' }],
      url: '/tournaments/{tournament_id}/stage_items/{stage_item_id}/inputs/{stage_item_input_id}',
      ...options,
      headers: {
        'Content-Type': 'application/json',
        ...options.headers,
      },
    });

/**
 * Start Next Round
 */
export const startNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostData,
    ThrowOnError
  >,
): RequestResult<
  StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostResponses,
  StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostResponses,
    StartNextRoundTournamentsTournamentIdStageItemsStageItemIdStartNextRoundPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stage_items/{stage_item_id}/start_next_round',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Matches To Schedule
 */
export const getMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGet = <
  ThrowOnError extends boolean = false,
>(
  options: Options<
    GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetData,
    ThrowOnError
  >,
): RequestResult<
  GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetResponses,
  GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetResponses,
    GetMatchesToScheduleTournamentsTournamentIdStageItemsStageItemIdUpcomingMatchesGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stage_items/{stage_item_id}/upcoming_matches',
    ...options,
  });

/**
 * Get Stages
 */
export const getStagesTournamentsTournamentIdStagesGet = <ThrowOnError extends boolean = false>(
  options: Options<GetStagesTournamentsTournamentIdStagesGetData, ThrowOnError>,
): RequestResult<
  GetStagesTournamentsTournamentIdStagesGetResponses,
  GetStagesTournamentsTournamentIdStagesGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetStagesTournamentsTournamentIdStagesGetResponses,
    GetStagesTournamentsTournamentIdStagesGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/stages',
    ...options,
  });

/**
 * Create Stage
 */
export const createStageTournamentsTournamentIdStagesPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateStageTournamentsTournamentIdStagesPostData, ThrowOnError>,
): RequestResult<
  CreateStageTournamentsTournamentIdStagesPostResponses,
  CreateStageTournamentsTournamentIdStagesPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateStageTournamentsTournamentIdStagesPostResponses,
    CreateStageTournamentsTournamentIdStagesPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stages',
    ...options,
  });

/**
 * Activate Next Stage
 */
export const activateNextStageTournamentsTournamentIdStagesActivatePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<ActivateNextStageTournamentsTournamentIdStagesActivatePostData, ThrowOnError>,
): RequestResult<
  ActivateNextStageTournamentsTournamentIdStagesActivatePostResponses,
  ActivateNextStageTournamentsTournamentIdStagesActivatePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    ActivateNextStageTournamentsTournamentIdStagesActivatePostResponses,
    ActivateNextStageTournamentsTournamentIdStagesActivatePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stages/activate',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Stage
 */
export const deleteStageTournamentsTournamentIdStagesStageIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteStageTournamentsTournamentIdStagesStageIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteStageTournamentsTournamentIdStagesStageIdDeleteResponses,
  DeleteStageTournamentsTournamentIdStagesStageIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteStageTournamentsTournamentIdStagesStageIdDeleteResponses,
    DeleteStageTournamentsTournamentIdStagesStageIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stages/{stage_id}',
    ...options,
  });

/**
 * Update Stage
 */
export const updateStageTournamentsTournamentIdStagesStageIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateStageTournamentsTournamentIdStagesStageIdPutData, ThrowOnError>,
): RequestResult<
  UpdateStageTournamentsTournamentIdStagesStageIdPutResponses,
  UpdateStageTournamentsTournamentIdStagesStageIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateStageTournamentsTournamentIdStagesStageIdPutResponses,
    UpdateStageTournamentsTournamentIdStagesStageIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/stages/{stage_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Teams
 */
export const getTeamsTournamentsTournamentIdTeamsGet = <ThrowOnError extends boolean = false>(
  options: Options<GetTeamsTournamentsTournamentIdTeamsGetData, ThrowOnError>,
): RequestResult<
  GetTeamsTournamentsTournamentIdTeamsGetResponses,
  GetTeamsTournamentsTournamentIdTeamsGetErrors,
  ThrowOnError
> =>
  (options.client ?? client).get<
    GetTeamsTournamentsTournamentIdTeamsGetResponses,
    GetTeamsTournamentsTournamentIdTeamsGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/tournaments/{tournament_id}/teams',
    ...options,
  });

/**
 * Create Team
 */
export const createTeamTournamentsTournamentIdTeamsPost = <ThrowOnError extends boolean = false>(
  options: Options<CreateTeamTournamentsTournamentIdTeamsPostData, ThrowOnError>,
): RequestResult<
  CreateTeamTournamentsTournamentIdTeamsPostResponses,
  CreateTeamTournamentsTournamentIdTeamsPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateTeamTournamentsTournamentIdTeamsPostResponses,
    CreateTeamTournamentsTournamentIdTeamsPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Delete Team
 */
export const deleteTeamTournamentsTournamentIdTeamsTeamIdDelete = <
  ThrowOnError extends boolean = false,
>(
  options: Options<DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteData, ThrowOnError>,
): RequestResult<
  DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteResponses,
  DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteErrors,
  ThrowOnError
> =>
  (options.client ?? client).delete<
    DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteResponses,
    DeleteTeamTournamentsTournamentIdTeamsTeamIdDeleteErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams/{team_id}',
    ...options,
  });

/**
 * Update Team By Id
 */
export const updateTeamByIdTournamentsTournamentIdTeamsTeamIdPut = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutData, ThrowOnError>,
): RequestResult<
  UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutResponses,
  UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutResponses,
    UpdateTeamByIdTournamentsTournamentIdTeamsTeamIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams/{team_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Update Team Logo
 */
export const updateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostData, ThrowOnError>,
): RequestResult<
  UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostResponses,
  UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostResponses,
    UpdateTeamLogoTournamentsTournamentIdTeamsTeamIdLogoPostErrors,
    ThrowOnError
  >({
    ...formDataBodySerializer,
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams/{team_id}/logo',
    ...options,
    headers: {
      'Content-Type': null,
      ...options.headers,
    },
  });

/**
 * Merge Team
 */
export const mergeTeamTournamentsTournamentIdTeamsTeamIdMergePost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<MergeTeamTournamentsTournamentIdTeamsTeamIdMergePostData, ThrowOnError>,
): RequestResult<
  MergeTeamTournamentsTournamentIdTeamsTeamIdMergePostResponses,
  MergeTeamTournamentsTournamentIdTeamsTeamIdMergePostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    MergeTeamTournamentsTournamentIdTeamsTeamIdMergePostResponses,
    MergeTeamTournamentsTournamentIdTeamsTeamIdMergePostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams/{team_id}/merge',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Split Team
 *
 * Distributes the members of a team over other teams and removes the emptied team, so a
 * team that is short of players can be dissolved into the remaining ones.
 */
export const splitTeamTournamentsTournamentIdTeamsTeamIdSplitPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<SplitTeamTournamentsTournamentIdTeamsTeamIdSplitPostData, ThrowOnError>,
): RequestResult<
  SplitTeamTournamentsTournamentIdTeamsTeamIdSplitPostResponses,
  SplitTeamTournamentsTournamentIdTeamsTeamIdSplitPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    SplitTeamTournamentsTournamentIdTeamsTeamIdSplitPostResponses,
    SplitTeamTournamentsTournamentIdTeamsTeamIdSplitPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams/{team_id}/split',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Create Multiple Teams
 */
export const createMultipleTeamsTournamentsTournamentIdTeamsMultiPost = <
  ThrowOnError extends boolean = false,
>(
  options: Options<CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostData, ThrowOnError>,
): RequestResult<
  CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostResponses,
  CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostResponses,
    CreateMultipleTeamsTournamentsTournamentIdTeamsMultiPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/tournaments/{tournament_id}/teams_multi',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get User
 */
export const getUserUsersMeGet = <ThrowOnError extends boolean = false>(
  options?: Options<GetUserUsersMeGetData, ThrowOnError>,
): RequestResult<GetUserUsersMeGetResponses, unknown, ThrowOnError> =>
  (options?.client ?? client).get<GetUserUsersMeGetResponses, unknown, ThrowOnError>({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/me',
    ...options,
  });

/**
 * Register User
 */
export const registerUserUsersRegisterPost = <ThrowOnError extends boolean = false>(
  options: Options<RegisterUserUsersRegisterPostData, ThrowOnError>,
): RequestResult<
  RegisterUserUsersRegisterPostResponses,
  RegisterUserUsersRegisterPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RegisterUserUsersRegisterPostResponses,
    RegisterUserUsersRegisterPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/users/register',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Register Demo User
 */
export const registerDemoUserUsersRegisterDemoPost = <ThrowOnError extends boolean = false>(
  options: Options<RegisterDemoUserUsersRegisterDemoPostData, ThrowOnError>,
): RequestResult<
  RegisterDemoUserUsersRegisterDemoPostResponses,
  RegisterDemoUserUsersRegisterDemoPostErrors,
  ThrowOnError
> =>
  (options.client ?? client).post<
    RegisterDemoUserUsersRegisterDemoPostResponses,
    RegisterDemoUserUsersRegisterDemoPostErrors,
    ThrowOnError
  >({
    responseType: 'json',
    url: '/users/register_demo',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Get Me
 */
export const getMeUsersUserIdGet = <ThrowOnError extends boolean = false>(
  options: Options<GetMeUsersUserIdGetData, ThrowOnError>,
): RequestResult<GetMeUsersUserIdGetResponses, GetMeUsersUserIdGetErrors, ThrowOnError> =>
  (options.client ?? client).get<
    GetMeUsersUserIdGetResponses,
    GetMeUsersUserIdGetErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{user_id}',
    ...options,
  });

/**
 * Update User Details
 */
export const updateUserDetailsUsersUserIdPut = <ThrowOnError extends boolean = false>(
  options: Options<UpdateUserDetailsUsersUserIdPutData, ThrowOnError>,
): RequestResult<
  UpdateUserDetailsUsersUserIdPutResponses,
  UpdateUserDetailsUsersUserIdPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    UpdateUserDetailsUsersUserIdPutResponses,
    UpdateUserDetailsUsersUserIdPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{user_id}',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });

/**
 * Put User Password
 */
export const putUserPasswordUsersUserIdPasswordPut = <ThrowOnError extends boolean = false>(
  options: Options<PutUserPasswordUsersUserIdPasswordPutData, ThrowOnError>,
): RequestResult<
  PutUserPasswordUsersUserIdPasswordPutResponses,
  PutUserPasswordUsersUserIdPasswordPutErrors,
  ThrowOnError
> =>
  (options.client ?? client).put<
    PutUserPasswordUsersUserIdPasswordPutResponses,
    PutUserPasswordUsersUserIdPasswordPutErrors,
    ThrowOnError
  >({
    responseType: 'json',
    security: [{ scheme: 'bearer', type: 'http' }],
    url: '/users/{user_id}/password',
    ...options,
    headers: {
      'Content-Type': 'application/json',
      ...options.headers,
    },
  });
